#pragma once

/** @file version.hpp
 *  @brief The library's own release version -- not to be confused with
 *         `wire::cFormatVersion` (wire.hpp).
 *
 *  Two numbers, two rates of change, kept deliberately apart: the library
 *  version below moves on every release, including releases that touch
 *  nothing on the wire; `wire::cFormatVersion` moves only when the on-disk
 *  contract itself changes, which is meant to be rare. Consumers that want
 *  "am I linked against a new enough Sub0Log" want this file; consumers
 *  that want "can I decode this segment" want wire.hpp instead.
 *
 *  Deliberately generated by nobody: a `configure_file`d header would break
 *  the "just add include/ to your include path, no add_subdirectory
 *  required" use a header-only library exists to keep. Instead the numbers
 *  are hand-written here and CMakeLists.txt asserts at configure time that
 *  `project(Sub0Log VERSION ...)` agrees with them, so the two cannot drift
 *  apart silently.
 */

#include <string_view>

#define SUB0LOG_VERSION_MAJOR 0
#define SUB0LOG_VERSION_MINOR 1
#define SUB0LOG_VERSION_PATCH 0

/// Single comparable integer, e.g. `#if SUB0LOG_VERSION >= 100` for >= 0.1.0.
/// Two decimal digits per component (minor/patch capped at 99) keeps the
/// arithmetic fixed-width and the comparison obviously correct at a glance,
/// which is what a preprocessor `#if` actually needs.
#define SUB0LOG_VERSION \
    (SUB0LOG_VERSION_MAJOR * 10000 + SUB0LOG_VERSION_MINOR * 100 + SUB0LOG_VERSION_PATCH)

// Stringized from the integer macros above, not spelled out separately --
// otherwise the string and the integers are two places to update in step.
#define SUB0LOG_DETAIL_STR(x) #x
#define SUB0LOG_DETAIL_STR_EXPAND(x) SUB0LOG_DETAIL_STR(x)
#define SUB0LOG_VERSION_STRING                                \
    SUB0LOG_DETAIL_STR_EXPAND(SUB0LOG_VERSION_MAJOR) "."       \
    SUB0LOG_DETAIL_STR_EXPAND(SUB0LOG_VERSION_MINOR) "."       \
    SUB0LOG_DETAIL_STR_EXPAND(SUB0LOG_VERSION_PATCH)

namespace sub0log {

/// "MAJOR.MINOR.PATCH" -- e.g. "0.1.0". Built from SUB0LOG_VERSION_STRING
/// above, which is itself built from the integer macros, so there is
/// exactly one place these digits are spelled out.
[[nodiscard]] constexpr std::string_view libraryVersion() noexcept
{
    return SUB0LOG_VERSION_STRING;
}

} // namespace sub0log
